# Use the official PostgreSQL image from the Docker Hub
FROM postgres:15-alpine

# Set environment variables to configure the PostgreSQL instance
ENV POSTGRES_USER=your_db_user
ENV POSTGRES_PASSWORD=your_db_password
ENV POSTGRES_DB=your_db_name

# Expose the default PostgreSQL port
EXPOSE 5432
